### PR TITLE
fix: catch babel parse errors

### LINKED ISSUE #197: Plugin throws less helpful errors when code has a SyntaxError
**Your Environment**

-   **Prettier version**: 3.4.2
-   **node version**: 22.12.0
-   **package manager**: pnpm@9.15.2
-   **IDE**: VSCode

**Describe the bug**

I've noticed that when a file has legitimate syntax errors, that this plugin will throw before prettier is able to throw.  I suspect it's just uncaught `babel/traverse` errors, and since the plugin is a preprocessor, it crashes the prettier run before prettier is able to throw.  That would be ok, if the errors from this plugin / babel were at least as helpful as the errors from prettier.  But what I've found is that they're aren't.  I'd like to propose that we wrap the babel parsing in a try catch and just write the errors to console, rather than throwing, so that we give prettier a chance to throw more helpful errors.

**To Reproduce**

Repro repo: https://github.com/michaelfaith/ianvs-prettier-plugin-sort-imports-bug

**Screenshots, code sample, etc**

screenshot of the repro

(first execution is running prettier without the plugin, and the second run is with the plugin)

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [x] I'm willing to fix this bug 🥇

### PR DESCRIPTION
**Pull request by michaelfaith**
This change updates the plugin to catch babel parsing errors, so that we can give prettier a chance to throw.  We're still writing an error to console, so that in the event that prettier doesn't end up throwing, we're still indicating that the import sorting failed.

screenshot of new behavior

Closes #197

### CODE REVIEW

File: src/preprocessors/preprocessor.ts [hunk 1]
```diff
@@ -22,7 +32,13 @@ export function preprocessor(code: string, options: PrettierOptions): string {
         parserOptions.allowReturnOutsideFunction = true;
     }
 
-    const ast = babelParser(code, parserOptions);
+    let ast;
+    try {
+        ast = babelParser(code, parserOptions);
```
Comment (michaelfaith) [inline src/preprocessors/preprocessor.ts:37]: I said in the original issue that it was babel.traverse that was throwing, but I mispoke; it was actually the parse that happens first.  So, I only wrapped the parse itself.

File: src/preprocessors/preprocessor.ts [hunk 2]
```diff
@@ -7,6 +7,16 @@ import { getCodeFromAst } from '../utils/get-code-from-ast';
...
 import { examineAndNormalizePluginOptions } from '../utils/normalize-plugin-options';
 
+const colors = {
+    red: '\x1b[31m',
+    yellow: '\x1b[33m'
+} as const;
+
+function colorText(text: string, color: keyof typeof colors): string {
+    const resetColor = '\x1b[0m';
+    return `${colors[color]}${text}${resetColor}`
```
Comment (fbartho) [inline src/preprocessors/preprocessor.ts:17]: We need to detect if the terminal/process/prettier has colors enabled before posting with colors, so that if they're piping this, we don't bake in these terminal codes for an environment that doesn't support it.

**Review by fbartho — CHANGES_REQUESTED** [review]
Looks good to me, other than the change needed for colors!

Thanks!

File: src/preprocessors/preprocessor.ts (hunk 2 above)
Comment (michaelfaith) [reply src/preprocessors/preprocessor.ts]: Went ahead and removed the colors.  Doesn't seem worth adding another library (or adding all the required code locally) for that.

File: src/preprocessors/preprocessor.ts [hunk 3]
```diff
@@ -22,7 +22,13 @@ export function preprocessor(code: string, options: PrettierOptions): string {
         parserOptions.allowReturnOutsideFunction = true;
     }
 
-    const ast = babelParser(code, parserOptions);
+    let ast;
```
Comment (fbartho) [inline src/preprocessors/preprocessor.ts:25]:
```suggestion
    let ast: ReturnType<typeof babelParser>;
```

**Review by fbartho — APPROVED** [review]
@IanVS will have to do the next steps, but this looks good to me!

thanks again!

**Comment by IanVS** [comment]
Thanks a ton, @michaelfaith, this will be very helpful.

**Review by IanVS — APPROVED** [review]
